// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kalilventura/vehicle-management/internal/shared/domain/entities"
	"github.com/kalilventura/vehicle-management/internal/shared/infrastructure/configuration"
	"github.com/kalilventura/vehicle-management/internal/vehicles"
	"github.com/kalilventura/vehicle-management/internal/vehicles/domain/commands"
	"github.com/kalilventura/vehicle-management/internal/vehicles/infrastructure/controllers"
	"github.com/kalilventura/vehicle-management/internal/vehicles/infrastructure/repositories"
	"os"
	"strconv"
)

// Injectors from wire.go:

func injectModules() []entities.HTTPModule {
	databaseSettings := injectDatabaseSettings()
	db := configuration.NewDatabaseClient(databaseSettings)
	gormVehiclesRepository := repositories.NewGormVehiclesRepository(db)
	saveVehicleCommand := commands.NewSaveVehicleCommand(gormVehiclesRepository)
	saveVehiclesController := controllers.NewSaveVehiclesController(saveVehicleCommand)
	getVehicleByIDCommand := commands.NewGetVehicleByIDCommand(gormVehiclesRepository)
	getVehicleByIdController := controllers.NewGetVehicleByIdController(getVehicleByIDCommand)
	listVehiclesCommand := commands.NewListVehiclesCommand(gormVehiclesRepository)
	listVehiclesController := controllers.NewListVehiclesController(listVehiclesCommand)
	module := vehicles.NewModule(saveVehiclesController, getVehicleByIdController, listVehiclesController)
	v := newModules(module)
	return v
}

// wire.go:

func injectSettings() *entities.Settings {
	port, _ := strconv.Atoi(os.Getenv("PORT"))
	return entities.NewSettings(port)
}

func injectDatabaseSettings() *entities.DatabaseSettings {
	host := os.Getenv("DB_HOST")
	name := os.Getenv("DB_NAME")
	port := os.Getenv("DB_PORT")
	user := os.Getenv("DB_USER")
	password := os.Getenv("DB_PASSWORD")
	dbSSL := os.Getenv("DB_SSL")
	return entities.NewDatabaseSettings(
		host,
		name,
		port,
		user,
		password,
		dbSSL,
	)
}

func newModules(vehiclesModule *vehicles.Module) []entities.HTTPModule {
	return []entities.HTTPModule{
		vehiclesModule,
	}
}
