// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kalilventura/vehicle-management/internal/shared/domain/entities"
	"github.com/kalilventura/vehicle-management/internal/vehicles"
	"github.com/kalilventura/vehicle-management/internal/vehicles/infrastructure/controllers"
	"os"
	"strconv"
)

// Injectors from wire.go:

func injectModules() []entities.HTTPModule {
	getVehiclesController := controllers.NewGetVehiclesController()
	module := vehicles.NewModule(getVehiclesController)
	v := newModules(module)
	return v
}

// wire.go:

func injectSettings() *entities.Settings {
	port, _ := strconv.Atoi(os.Getenv("PORT"))
	return entities.NewSettings(port)
}

func newModules(vehiclesModule *vehicles.Module) []entities.HTTPModule {
	return []entities.HTTPModule{
		vehiclesModule,
	}
}
