name: Golang Workflow

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: 'write' # delivery-release

jobs:
  tests_test_all:
    name: 'tests > test-all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
          cache: false
      - name: Install dependencies
        run: |
          cd cmd
          go get .
      - name: Build
        run: go build -v ./...
      - name: Ensure test script is executable
        run: chmod +x .github/scripts/tests/run_tests.sh

      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@main
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Run tests
        run: make test

      - name: Publish test reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.txt
            junit.xml
            cobertura.xml

  docker-build-and-push:
    name: 'docker > build and push'
    runs-on: ubuntu-latest
    needs: [tests_test_all]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Validate Docker Hub repository
        id: validate-repo
        run: |
          REPO_NAME="${{ secrets.DOCKER_REPOSITORY_NAME }}"
          NAMESPACE="${{ secrets.DOCKER_USERNAME }}"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${NAMESPACE}/${REPO_NAME}/")

          if [ "$RESPONSE" -eq 200 ]; then
            echo "Repository ${NAMESPACE}/${REPO_NAME} exists."
          elif [ "$RESPONSE" -eq 404 ]; then
            echo "Repository ${NAMESPACE}/${REPO_NAME} does not exist."
            exit 1
          else
            echo "Failed to check repository existence. HTTP status code: ${RESPONSE}"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ github.sha }}
